from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import SalaryAdvanceRequest, Employee, Profile, LoanRequest
from django.core.exceptions import ValidationError
from django.db import transaction


# ================================================================
# Sign Up Form
# ================================================================
class SignUpForm(UserCreationForm):
    """
    Custom user signup form.
    - Requires Staff ID and Staff Email.
    - Verifies that Staff ID and Email correspond to an existing Employee.
    - Creates a User and links it to Employee + Profile atomically.
    """

    staffid = forms.CharField(
        max_length=150,
        required=True,
        label="Staff ID",
        widget=forms.TextInput(attrs={'placeholder': 'Enter your Staff ID'})
    )
    email = forms.EmailField(
        required=True,
        label="Staff Email",
        widget=forms.EmailInput(attrs={'placeholder': 'Enter your staff email'})
    )

    class Meta:
        model = User
        fields = ['staffid', 'email', 'password1', 'password2']

    def clean_staffid(self):
        staffid = (self.cleaned_data.get('staffid') or '').strip()
        if not staffid:
            raise ValidationError("Staff ID is required.")
        if User.objects.filter(username__iexact=staffid).exists():
            raise ValidationError("An account already exists for this Staff ID.")
        if not Employee.objects.filter(staff_id__iexact=staffid).exists():
            raise ValidationError("No employee found with that Staff ID. Contact HR.")
        return staffid

    def clean_email(self):
        email = (self.cleaned_data.get('email') or '').strip().lower()
        if not email:
            raise ValidationError("Email is required.")
        if User.objects.filter(email__iexact=email).exists():
            raise ValidationError("An account with this email already exists.")
        return email

    def clean(self):
        cleaned = super().clean()
        staffid = (cleaned.get('staffid') or '').strip()
        email = (cleaned.get('email') or '').strip().lower()
        if staffid and email:
            if not Employee.objects.filter(staff_id__iexact=staffid, email__iexact=email).exists():
                raise ValidationError("Staff ID and Email do not match our employee records.")
        return cleaned

    @transaction.atomic
    def save(self, commit=True):
        staffid = self.cleaned_data['staffid'].strip()
        email = self.cleaned_data['email'].strip().lower()
        password = self.cleaned_data['password1']

        # Create User
        user = User.objects.create_user(username=staffid, email=email, password=password)

        # Sync names from Employee record
        try:
            employee = Employee.objects.get(staff_id__iexact=staffid)
            name_parts = (employee.full_name or "").strip().split(" ", 1)
            user.first_name = name_parts[0] if len(name_parts) >= 1 else ""
            user.last_name = name_parts[1] if len(name_parts) > 1 else ""
            user.save(update_fields=['first_name', 'last_name'])
        except Employee.DoesNotExist:
            employee = None

        # Create or update Profile
        profile, _ = Profile.objects.get_or_create(user=user)
        if employee:
            profile.employee = employee
        profile.save()

        return user


# ================================================================
# Salary Advance Request Form
# ================================================================
class SalaryAdvanceForm(forms.ModelForm):
    class Meta:
        model = SalaryAdvanceRequest
        fields = ['amount', 'reason']
        widgets = {
            'amount': forms.NumberInput(attrs={
                'id': 'amount',
                'placeholder': 'Enter amount',
                'max': '50000',
                'required': True
            }),
            'reason': forms.Textarea(attrs={
                'id': 'reason',
                'placeholder': 'Optional: Enter reason for request'
            }),
        }


# ================================================================
# Employee Form
# ================================================================
class EmployeeForm(forms.ModelForm):
    """
    Form for adding/editing Employee records.
    staff_id is auto-generated by the model.
    """
    class Meta:
        model = Employee
        fields = [
            'full_name', 'national_id', 'dob',
            'date_joined', 'department', 'job_title',
            'employment_type', 'salary', 'email', 'phone', 'address'
        ]
        widgets = {
            'dob': forms.DateInput(attrs={'type': 'date'}),
            'date_joined': forms.DateInput(attrs={'type': 'date'}),
            'address': forms.Textarea(attrs={'rows': 3}),
        }


# ================================================================
# Profile Update Form
# ================================================================
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["profile_picture"]


# ================================================================
# Loan Request Form
# ================================================================
# ================================================================
# Loan Request Form (updated to support 'employee')
# ================================================================
class LoanRequestForm(forms.ModelForm):
    class Meta:
        model = LoanRequest
        fields = ['amount', 'repayment_period', 'reason']
        widgets = {
            'amount': forms.NumberInput(attrs={
                'id': 'loanAmount',
                'placeholder': 'Enter loan amount',
                'required': True
            }),
            'repayment_period': forms.Select(attrs={
                'id': 'repaymentPeriod',
                'required': True
            }, choices=[(6, "6 Months"), (12, "12 Months"), (18, "18 Months"), (24, "24 Months")]),
            'reason': forms.Textarea(attrs={
                'id': 'reason',
                'placeholder': 'Optional: Enter reason for request'
            }),
        }

    def __init__(self, *args, employee=None, **kwargs):
        """
        Allow passing an 'employee' argument when initializing the form.
        Useful for dynamic validation or display limits.
        """
        super().__init__(*args, **kwargs)
        self.employee = employee

        # Optionally display context to the user
        if employee:
            # Example: dynamic help text based on employee salary
            max_loan = employee.salary * 2 if employee.salary else 0
            self.fields["amount"].help_text = f"Maximum allowed loan: KSh {max_loan:,.2f}"

    def clean_amount(self):
        """
        Validate loan amount: cannot exceed twice the employee’s salary.
        """
        amount = self.cleaned_data.get("amount")
        if self.employee and amount and amount > (self.employee.salary * 2):
            raise forms.ValidationError("Requested amount exceeds your loan limit (2× salary).")
        return amount
