from django.urls import path
from .views import (
    index,
    application,
    login_view,
    signup,
    home,
    request_form,
    internal_loan,
    message_finance,
    chat_finance,
    support_query,
    signup_sucess,
    admin_dashboard,
    employee_creation,
    employee_creation_success,
    update_profile,
    admin_home,
    request_form_success,
    internal_loan_success,
    employee_list,
    finance,
    finance_message_centre,
    finance_chat_detail,
    redirect_after_login,         
    finance_salary_request,       
    finance_internal_loan_request,
    hr_home, 
    approve_salary_request,
    reject_salary_request,
    hr_departments, 
    payroll_payslips,
    hr_track_performance,
    attendance_tracking,
    hr_message_centre,
    hr_loan_requests,
    hr_reports,
    hr_leaves_offs,
    employee_today,
    hr_settings,
    hr_appraissals,
    hr_profile
          
)

urlpatterns = [
    path('', index, name='index'),
    path('application/', application, name='application'),
    path('login/', login_view, name='login'),
    path('signup/', signup, name='signup'),
    path('home/', home, name='home'),
    path('request_form/', request_form, name='request_form'),
    path('internal_loan/', internal_loan, name='internal_loan'),
    path('message_finance/', message_finance, name='message_finance'),
    path('chat_finance/', chat_finance, name='chat_finance'),
    path('support_query/', support_query, name='support_query'),
    path('signup_sucess/', signup_sucess, name='signup_sucess'),
    path('admin/', admin_dashboard, name='admin'),
    path('employee_creation/', employee_creation, name='employee_creation'),
    path('employee_creation_success/', employee_creation_success, name='employee_creation_success'),
    path('update_profile/', update_profile, name='update_profile'),
    path('admin_home/', admin_home, name='admin_home'),
    path('request_form_success/', request_form_success, name='request_form_success'),
    path('internal_loan_success/', internal_loan_success, name='internal_loan_success'),
    path('employee_list/', employee_list, name='employee_list'),
    path('finance/', finance, name='finance'),
    path('finance_message_centre/', finance_message_centre, name='finance_message_centre'),
    path("finance_chat_detail/<int:user_id>/", finance_chat_detail, name="finance_chat_detail"),
  
    path('redirect_after_login/', redirect_after_login, name='redirect_after_login'),
    path('finance_salary_request/', finance_salary_request, name='finance_salary_request'),
    path('finance_internal_loan_request/', finance_internal_loan_request, name='finance_internal_loan_request'),
    path('hr_home/', hr_home, name='hr_home'),
    path('hr/departments/', hr_departments, name='hr_departments'),
    path('hr/payroll/', payroll_payslips, name='payroll_payslips'),
    path('hr/track-performance/', hr_track_performance, name='hr_track_performance'),
 

    path('hr/attendance/', attendance_tracking, name='attendance_tracking'),
    path('hr/messages/', hr_message_centre, name='hr_message_centre'),
    path('hr/loan-requests/', hr_loan_requests, name='hr_loan_requests'),
    path('hr/reports/', hr_reports, name='hr_reports'),
    path('hr/departments/', hr_departments, name='hr_departments'),
    path('hr/employees-today/', employee_today, name='employee_today'),
    path('hr/leaves-offs/', hr_leaves_offs, name='hr_leaves_offs'),
    path('hr/settings/', hr_settings, name='hr_settings'),
    path('hr/appraissals/', hr_appraissals, name='hr_appraissals'),
    path('hr/profile/', hr_profile, name='hr_profile'),






    path('finance/requests/', finance_salary_request, name='finance_salary_request'),
    path('finance/requests/<int:pk>/approve/', approve_salary_request, name='approve_salary_request'),
    path('finance/requests/<int:pk>/reject/', reject_salary_request, name='reject_salary_request'),
]


