# Generated by Django 5.2.4 on 2025-09-11 16:24

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpayapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('staff_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
                ('department', models.CharField(choices=[('Finance', 'Finance'), ('HR', 'HR'), ('IT', 'IT'), ('Operations', 'Operations')], max_length=50)),
                ('job_title', models.CharField(max_length=100)),
                ('employment_type', models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Contract'), ('Internship', 'Internship')], max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='salaryadvancerequest',
            name='date_requested',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='salaryadvancerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
