# Generated by Django 5.2.4 on 2025-09-15 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpayapp', '0002_employee_alter_salaryadvancerequest_date_requested_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='staffid',
        ),
        migrations.AddField(
            model_name='profile',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smartpayapp.employee'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default_avatar.png', null=True, upload_to='profile_pics/'),
        ),
    ]
