# Generated by Django 5.2.5 on 2025-09-14 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpayapp', '0003_remove_profile_department_remove_profile_staffid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalLoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('repayment_period', models.IntegerField(choices=[(6, '6 Months'), (12, '12 Months'), (18, '18 Months'), (24, '24 Months')])),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartpayapp.employee')),
            ],
        ),
    ]
