# Generated by Django 5.2.6 on 2025-09-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpayapp', '0006_alter_employee_staff_id_alter_profile_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='staff_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
