# Generated by Django 5.2.6 on 2025-09-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpayapp', '0007_alter_employee_staff_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='staff_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
