# Generated by Django 5.2.6 on 2025-09-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpayapp', '0008_alter_employee_staff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR'), ('finance', 'Finance'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
