# Generated by Django 5.2.6 on 2025-09-29 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpayapp', '0009_remove_profile_role_employee_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryadvancerequest',
            name='action_datetime',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='salaryadvancerequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_salary_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
