# Generated by Django 5.2.3 on 2025-10-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpayapp', '0012_employeeleavebalance_leaverequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='total_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
