# Generated by Django 5.2.3 on 2025-10-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpayapp', '0013_alter_leaverequest_total_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
