# Generated by Django 5.2.3 on 2025-10-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpayapp', '0014_alter_leaverequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
