# Generated by Django 5.2.3 on 2025-10-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpayapp', '0015_alter_leaverequest_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Off Day', 'Off Day'), ('Annual Leave', 'Annual Leave')], max_length=20),
        ),
    ]
